#!/usr/bin/env python3

"""overlay_filter

Simplistic pandoc filter to include beamer overlay specifications on
inline tex in markdown

Whereas in normal beamer LaTeX you'd write

    \cmd<overlay>{...}

in markdown write

    \cmd{<overlay>}{...}

then process with

    pandoc --filter overlay_filter

Environments are passed through to LaTeX, so there's no need to filter
them; write onlyenv as normal, for example.
"""

import re
from pandocfilters import toJSONFilter


ov_pat = re.compile(r'^(\\\w+)(\{<[^>]+>})(.*)$',flags=re.DOTALL)

def overlay_filter(key, value, fmt, meta):
    if key == 'RawInline' and value[0] == 'tex':
        m = ov_pat.match(value[1])
        if m:
            c = m.group(1)
            c += re.sub(r'^\{|}$', "", m.group(2))
            c += m.group(3)
            return { "t": "RawInline", "c": ["tex", c] }

if __name__ == "__main__":
    toJSONFilter(overlay_filter)
