toc: true
toc-title: "Outline"
toc-depth: 1
format-links: false

format:
  html: 
    embed-resources: true
  revealjs:
    theme: [default, clean.scss]
    menu:
      side: left
    slide-number: true
    date-format: long
    embed-resources: true
